### ISSUE TITLE
[Request] add a open source license to the project

### ISSUE THREAD

**Issue by harryherbig** [gb9k/GameboyMacro#5]
# what
Please add a license to your repository

# how
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

# why
Open source licenses enable others to freely use, change, and distribute the project in your repository. For more information on repository licenses, see:
https://docs.github.com/en/free-pro-team@latest/articles/licensing-a-repository

## motivation
I'd like to use your files as a basis for creating my own design. 
Because your repository doesn't contain a license I am unsure about the legal situation for publishing a remix on pages like thingiverse or similar sites. 

# personal addition
I already created a remix by importing stl files from thingiverse that derived from your design, but the mesh bodies are hard to work with, so I am really happy that you added the f3d file so I would like to redo my design based on it. 

I projected the outline and button positions to create a custom front. This is the result of my remix:

https://reddit.com/r/gameboymacro/comments/jh269r/gameboy_macro_mk2_3dprinted_faceplate_i_created/

I designed it with the goals:
•  an indent for the originally upper screen lense, so it sits flush
•  a Game Boy logo (probably should be omitted when published to thingiverse)
•  full screen sized opening because I use it with an #r4card running #gbarunner2 and #gameyob with #ysmenu and need to see the whole display in menus and gameyob can also stretch games to fullscreen  
•  smooth filets on the indents around the buttons
•  .2 mm thick layer at the LED opening to see the light also with dark filaments and not fearing water or debris getting in

**Comment by gb9k** [comment]
My bad, MIT added. I'm so stoked you're having fun with it and your project is looking nice!

**Comment by harryherbig** [comment]
hey @gb9k 
I forked your repo and released my designs.
After checking with https://choosealicense.com/ I came to the conclusion, that the MIT license might not be the right one, as it only applies to software.

What do you think about: https://choosealicense.com/licenses/cc-by-sa-4.0/

It has the following conditions, which I think should be appropriate:
- License and copyright notice
- Same license
- State changes

Looking forward to your response.
